### ISSUE TITLE
Running JoSH without category name

### ISSUE THREAD

**Issue by nareshr8** [yumeng5/JoSH#3]
If I have to run JoSH having the hierarchy in hand and not its name, is that possible. I would like to give the keywords around for suggesting the category name instead. Did you do any experiments around it. Is there any paper you could refer for instance. Any help is appreciated. 

Thanks in advance

**Comment by yumeng5** [comment]
Hi,

As mentioned in the [README](https://github.com/yumeng5/JoSH#corpus-and-inputs), you can provide arbitrary number of seed words in each line (at least 1 per category; if there are multiple seed words, separate them with whitespace characters) of the `category_names.txt` file, just note that you need to ensure that every provided seed word appears in the vocabulary of the corpus.

Best,
Yu
