### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'AutoPhrase/models/NEW/segmentation.txt'

### ISSUE THREAD

**Issue by ShreyaGupta08** [yumeng5/JoSH#4]
I followed all the steps of adding my corpus to the datasets folder by creating the text.txt file, category_names.txt file (ensuring each word appears in the corpus) and taxonomy.txt file. But when I run auto_phrase.sh I get the following error:

```
Traceback (most recent call last):
  File "utils.py", line 48, in <module>
    phrase_process()
  File "utils.py", line 11, in phrase_process
    f = open(os.path.join('AutoPhrase', 'models', args.dataset, 'segmentation.txt'))
FileNotFoundError: [Errno 2] No such file or directory: 'AutoPhrase/models/NEW/segmentation.txt'
```

The complete output of running auto_phase.sh is the following:

![image](https://user-images.githubusercontent.com/40699385/103521481-d75e1a80-4e9e-11eb-8329-29fbab9dba96.png)
![image](https://user-images.githubusercontent.com/40699385/103521535-ef359e80-4e9e-11eb-84b5-5aeba1fe775c.png)
![image](https://user-images.githubusercontent.com/40699385/103521559-fb216080-4e9e-11eb-9df8-f94017ca39e8.png)

My dataset folder is named 'who' and the dataset directory and raw text file were appropriately directed in auto_phase.sh

Any help appreciated. Thanks!

**Comment by yumeng5** [comment]
Hi Shreya,

Thanks for letting me know the issue. It seemed that there were some missing files in the AutoPhrase directory for preprocessing. I just updated the [AutoPhrase.zip](https://github.com/yumeng5/JoSH/blob/master/preprocess/AutoPhrase.zip) file, could you update it and see if it resolves the issue?

Thanks,
Yu

**Comment by ShreyaGupta08** [comment]
Thanks Yu for getting back. I'm still getting the same error. Attaching screenshots of the terminal output:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/40699385/103845405-030d1a80-50c2-11eb-8cb0-3814764591ec.png">
<img width="799" alt="image" src="https://user-images.githubusercontent.com/40699385/103845425-0e604600-50c2-11eb-8073-b3a4dec219b7.png">

**Comment by yumeng5** [comment]
Hi Shreya,

Thanks for posting the error message. Actually, I can run the updated AutoPhrase without errors on my side. Judging from your screenshot, I believe the first error occurred at [line 131](https://github.com/yumeng5/JoSH/blob/26cb0d1f5ef4a518411fce774019b8defe27cd44/preprocess/auto_phrase.sh#L130) of `auto_phrase.sh` and it seemed that you were not able to execute `./bin/segphrase_train` and `./bin/segphrase_segment`. I think this may not be related to the AutoPhrase code but your specific system setting. Perhaps you could look for solutions like [this](https://superuser.com/questions/435988/how-can-i-resolve-the-error-cannot-execute-binary-file).

Best,
Yu
