### ISSUE TITLE
MacOS X compatibility

### ISSUE THREAD

**Issue by jsedoc** [yumeng5/JoSH#5]
Hi, first off, thanks for your great work.

I just want you to be aware that there's an issue making your code run on Mac OS X. 
In josh.c you are using 

`
`fgetc_unlocked

but this is not a standard function and is available only on some Linux platforms.

**Comment by yumeng5** [comment]
Hi @jsedoc,

Thanks for trying out the code and letting me know the issue. I've updated the code to replace the `fgetc_unlocked` function. Please let me know if you still have any other issues running the code.

Thanks,
Yu

**Comment by jsedoc** [comment]
works TY!
