### ISSUE TITLE
Autophrase zip file includes binaries segphrase_train and segphrase_segment

### ISSUE THREAD

**Issue by jsedoc** [yumeng5/JoSH#6]
I think in the zip file you mistakenly checked in the bin folder, so this will make the autophrase not work on other architectures like MacOS X.

**Comment by yumeng5** [comment]
Hi @jsedoc,

Thanks for pointing out the issue. I compiled AutoPhrase on a Linux system so the binaries may not work on other systems. You could refer to the [AutoPhrase requirement](https://github.com/shangjingbo1226/AutoPhrase#requirements) to install the corresponding requirements for your system and rebuild the binaries (by running `compile.sh` under the AutoPhrase directory).

Thanks,
Yu
