### ISSUE TITLE
Predicted Category Label for Document d

### ISSUE THREAD

**Issue by Fenerator** [yumeng5/JoSH#8]
Is there already implemented a function to get not only top-k words per category, but to also get the predicted category label for each document (as stated by Eq. 4)?

**Comment by yumeng5** [comment]
Hi @Fenerator ,

The document assignment part is not included in the code, but it can be done very easily: The code will generate category embeddings (saved at the path specified by `-tree-emb`); the document embeddings can be saved via a similar process as [here](https://github.com/yumeng5/CatE/blob/d17640eeb0efd1eb881563f23df5bd3f8e8c81af/src/cate.c#L930-L942). Once you have the document embeddings and category embeddings, you could directly use the embedding cosine similarity to derive the category labels.

I hope this helps. Let me know if you have any other questions.

Best,
Yu
